{-# LANGUAGE TypeSynonymInstances #-}

import Test.QuickCheck
import Data.Monoid
import Text.BlazeHtml.Text (Text)
import qualified Text.BlazeHtml.Text as T
import Text.BlazeHtml.Internal.Html
import Text.BlazeHtml.Render.HtmlIO
import Text.BlazeHtml.Render.HtmlText
import Text.BlazeHtml.Render.HtmlPrettyText
import Text.BlazeHtml.Render.HtmlByteString
import System.IO
import System.IO.Unsafe (unsafePerformIO)

-- Must implement an Eq instance for each Html instance we test
instance Eq HtmlText where
    a == b = renderHtmlText a == renderHtmlText b

instance Eq HtmlIO where
    a == b = unsafePerformIO $ fileCompare a b
      where
        fileCompare a b = do
            -- Output the HTML to temp files
            (aname, ahandle) <- openTempFile "/tmp" "htmliotest.html"
            renderHtmlIO ahandle a
            hFlush ahandle
            (bname, bhandle) <- openTempFile "/tmp" "htmliotest.html"
            renderHtmlIO bhandle b
            hFlush bhandle
            -- Read in the resulting data and compare it
            adata <- hGetContents ahandle
            hClose ahandle
            bdata <- hGetContents bhandle
            hClose bhandle
            return (adata == bdata)

instance Eq HtmlPrettyText where
    a == b = renderHtmlPrettyText a == renderHtmlPrettyText b

instance Eq HtmlByteString where
    a == b = renderHtmlByteString a == renderHtmlByteString b

newtype SpecialChar = SC { unSC :: Char } deriving Show
instance Arbitrary SpecialChar where
   arbitrary = do 
      x <- oneof [choose ('\0','\55295'), choose ('\57344','\1114111')]
      return (SC x)

instance Arbitrary Text where
    arbitrary     = T.pack `fmap` arbitrary

-- The output of these Arbitrary instances can be examined using the sample'
-- function, for example:
--
-- > sample' arbitrary :: IO [Text]

-- Quickcheck property definitions

prop_RenderEmpty :: (Html h, Eq h) => h -> Bool
prop_RenderEmpty h = renderUnescapedText mempty == h

prop_RenderDistrib :: (Html h, Eq h) => h -> Text -> Text -> Bool
prop_RenderDistrib h t1 t2 = left == right
  where
    left = h `mappend` renderUnescapedText t1 `mappend` renderUnescapedText t2
    right = h `mappend` renderUnescapedText (t1 `mappend` t2)

prop_SetAttribUnescaped :: (Html h, Eq h) => h -> [Attribute] -> Text -> Bool
prop_SetAttribUnescaped h a t = left == right
  where
    left = h `mappend` setUnescapedAttributes a (renderUnescapedText t)
    right = h `mappend` (renderUnescapedText t)

prop_AddAttribUnescaped :: (Html h, Eq h) => h -> [Attribute] -> Text -> Bool
prop_AddAttribUnescaped h a t = left == right
  where
    left = h `mappend` addUnescapedAttributes a (renderUnescapedText t)
    right = h `mappend` (renderUnescapedText t)

-- The Html object passed in MUST have an outer tag, so attributes can be set
prop_SetAttribOverwrite :: (Html h, Eq h) => h -> [Attribute] -> [Attribute] -> Text -> Bool
prop_SetAttribOverwrite h a1 a2 t = left == right
  where
    left = setUnescapedAttributes a1 (setUnescapedAttributes a2 h)
    right = setUnescapedAttributes a2 h

-- Example of collecting the data generated by the Arbitrary instance:
--
-- prop_SetAttribOverwrite :: (Html h, Eq h) => h -> [Attribute] -> [Attribute] -> Text -> Property
-- prop_SetAttribOverwrite h a1 a2 t = collect t $ left == right
--   where
--     left = setUnescapedAttributes a1 (setUnescapedAttributes a2 h)
--     right = setUnescapedAttributes a2 h

-- The Html object passed in MUST have an outer tag, so attributes can be set
prop_AddSetAttribOverwrite :: (Html h, Eq h) => h -> [Attribute] -> [Attribute] -> Text -> Bool
prop_AddSetAttribOverwrite h a1 a2 t = left == right
  where
    left = addUnescapedAttributes a1 (setUnescapedAttributes a2 h)
    right = setUnescapedAttributes a2 h


prop_AddAddAttrib :: (Html h, Eq h) => h -> [Attribute]-> [Attribute] -> Text -> Bool
prop_AddAddAttrib h a1 a2 t = left == right
  where
    left = addUnescapedAttributes a1 (addUnescapedAttributes a2 h)
    right = addUnescapedAttributes (a2 `mappend` a1) h

-- Utility functions
orangeAttribs = [(T.pack("orange"), T.pack("mandarin"))]
appleAttribs = [(T.pack("apple"), T.pack("bramley"))]

pHtmlText :: HtmlText
pHtmlText = renderLeafElement $ T.pack "p"

pHtmlIO :: HtmlIO
pHtmlIO = renderLeafElement $ T.pack "p"

pHtmlPrettyText :: HtmlPrettyText
pHtmlPrettyText = renderLeafElement $ T.pack "p"

pHtmlByteString :: HtmlByteString
pHtmlByteString = renderLeafElement $ T.pack "p"

runHtmlTests empty pelem = do
    quickCheck $ prop_RenderEmpty empty
    quickCheck $ prop_RenderDistrib empty
    quickCheck $ prop_SetAttribUnescaped empty orangeAttribs
    quickCheck $ prop_AddAttribUnescaped empty orangeAttribs
    quickCheck $ prop_SetAttribOverwrite pelem orangeAttribs appleAttribs
    quickCheck $ prop_AddSetAttribOverwrite pelem orangeAttribs appleAttribs
    quickCheck $ prop_AddAddAttrib pelem orangeAttribs appleAttribs
     
runTests = do
    runHtmlTests (mempty :: HtmlText) pHtmlText
    runHtmlTests (mempty :: HtmlIO) pHtmlIO
    runHtmlTests (mempty :: HtmlPrettyText) pHtmlPrettyText
    runHtmlTests (mempty :: HtmlByteString) pHtmlByteString
 
printTests = do
    putStrLn $ T.unpack $ renderHtmlText $ setUnescapedAttributes orangeAttribs pHtmlText
    putStrLn $ T.unpack $ renderHtmlText $ setUnescapedAttributes appleAttribs (setUnescapedAttributes orangeAttribs pHtmlText)
    putStrLn $ T.unpack $ renderHtmlText $ addUnescapedAttributes (appleAttribs `mappend` orangeAttribs) pHtmlText
